all:
	gcc lab5client.c -o client
	gcc lab5server.c -o server
client:
	gcc lab5client.c -o client
server:
	gcc lab5server.c -o server
clean:
	clear
	rm -f client
	rm -f server
	rm -f core.*
	rm -f vgcore.*
